function [Rba,M] = Rotations(in1)
%ROTATIONS
%    [RBA,M] = ROTATIONS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Feb-2021 14:38:27

psi = in1(3,:);
rho = in1(1,:);
theta = in1(2,:);
t2 = cos(psi);
t3 = cos(rho);
t4 = cos(theta);
t5 = sin(psi);
t6 = sin(rho);
t7 = sin(theta);
t8 = t2.*t4;
t9 = t4.*t5;
t10 = -t9;
Rba = reshape([t8,t3.*t5+t2.*t6.*t7,t5.*t6-t2.*t3.*t7,t10,t2.*t3-t5.*t6.*t7,t2.*t6+t3.*t5.*t7,t7,-t4.*t6,t3.*t4],[3,3]);
if nargout > 1
    M = reshape([t8,t10,t7,t5,t2,0.0,0.0,0.0,1.0],[3,3]);
end
