function [W,RHS] = BallAndBeamODEMatrices(in1,To,in3)
%BALLANDBEAMODEMATRICES
%    [W,RHS] = BALLANDBEAMODEMATRICES(IN1,TO,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Feb-2021 22:46:07

J = in3(1,:);
M = in3(2,:);
R = in3(3,:);
dtheta = in1(4,:);
theta = in1(2,:);
x = in1(1,:);
t2 = sin(theta);
t3 = M.*R.*(3.0./5.0);
t4 = -t3;
W = reshape([M.*(7.0./5.0),t4,t4,J+M.*R.^2.*(7.0./5.0)+M.*x.^2],[2,2]);
if nargout > 1
    RHS = [-t2-M.*dtheta.^2.*x;To+R.*t2-x.*cos(theta)];
end
