function p = BallPosition(in1,in2)
%BALLPOSITION
%    P = BALLPOSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Feb-2021 22:46:07

R = in2(3,:);
theta = in1(2,:);
x = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
p = [-R.*t3+t2.*x;R.*t2+t3.*x];
