function [dstate] = PendulumDynamics(t, x, F, parameters)
%PENDULUMODEMATRICES
%    [W,RHS] = PENDULUMODEMATRICES(IN1,F,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Feb-2021 19:18:47
% state = [q;dq];
% param = [m;M;L;g];
q = x(1:3);
dq = x(4:6);

[W, RHS] = PendulumODEMatrices(x, F, parameters);
dstate = [dq; W\RHS];
end
